
import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar/Navbar";
import { Toaster } from "@/components/ui/sonner";

import MySession from "@/components/MySession/MySession";
import Footer from "@/components/Footer/Footer";



const inter = Exo({subsets:['latin'],variable:'--font-exo'});

export const metadata: Metadata = {
  title: "Fresh Cart",
  description: "Generated by create Kholoud",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", inter.variable)}>
      <body
        className={`antialiased`}
      >
        {/* حطيت الابلكيشن جوا عشان اقدر استخدمها مع كله  */}
        <MySession >
       <Navbar/> 
       <Toaster/>
      
    

<main className="pt-18 md:pt-24 lg:pt-27 min-h-[calc(100vh-200px)]">
    {children}
</main>
       
         <Footer />
        </MySession>
       
      </body>
    </html>
  );
}
